# create order

POST {{host-url}}/order/create
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "temperature": 36.6,
  "symptoms": "Болит голова, живот, нога, глаза"
}

###

## взять заявку
POST {{host-url}}/order/accept
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "order_id": 3
}

###

## Получить все
GET {{host-url}}/order/all
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

## Получить только новые
GET {{host-url}}/order/new?limit=2&offset=1
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



###

## Получить только свои текущие заявки
GET {{host-url}}/order/current
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###
## Получить только свои выписанные заявки
GET {{host-url}}/order/discharged
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###
