# create order

POST {{host-url}}/order/create
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "temperature": 36.6,
  "symptoms": "Болит голова, живот, нога, глаза"
}

###

## взять заявку
POST {{host-url}}/order/accept
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "order_id": 1
}

###
